name: Master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Lint, test and build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run nx -- run-many --all --target=lint
      - name: Run unit tests
        run: npm run nx -- run-many --all --target=test --code-coverage
        env:
          CI: true
      - name: Run e2e tests
        run: npm run e2e
        env:
          CI: true
      - name: Build website
        run: npm run nx -- run-many --all --target=build
      - name: Report coverage
        uses: codecov/codecov-action@v1
